### ISSUE TITLE
Small typos in code snippets in "Fuzzing RDPEGFX with "what the fuzz"

### ISSUE THREAD

**Issue by 0vercl0k** [thalium/blog#10]
Hello!

Thanks for writing up your journey fuzzing the RDPEGFX component of RDP, I really enjoyed the preso/blog/conversations at the event! I noticed small typos in the blogpost where in some statements, here is an example (notice the `!`):
```C
  const uint64_t pWPP_GLOBAL_Control =
      g_Dbg.GetSymbol("mstscax!WPP_GLOBAL_Control");
  !g_Backend->VirtWriteStruct(Gva_t(pWPP_GLOBAL_Control),
                              &pWPP_GLOBAL_Control);
```

Cheers!

**Comment by clslgrnc** [comment]
Indeed, I'll take a look.

Thanks
